name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: theguptaji/bookstore_items-api/items-api
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
